theme: jekyll-theme-cayman

# title: [Style-sensitive Word Vectors]
# tagline: [Learning Style-sensitive Word Vectors from Stylistically Consistent Utterances — ACL2018]
# description: [Learning Style-sensitive Word Vectors from Stylistically Consistent Utterances — ACL2018]
